### ISSUE TITLE
Can't run the example

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-CLI#1]
I have the following error:

```
tom@ens-laptop:~$ python3 -m ppp_cli "Where is ENS de Lyon?"

Response ():
    45.729722222222, 4.8269444444444
Traceback (most recent call last):
  File "/usr/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "./ppp_cli/__main__.py", line 26, in <module>
    main.main(args.api, args.id, args.language, args.parse, args.request)
  File "./ppp_cli/main.py", line 17, in main
    prettyprint(response)
  File "./ppp_cli/prettyprint.py", line 89, in prettyprint
    return prettyprinter(node, indent+1)
  File "./ppp_cli/prettyprint.py", line 49, in response
    prettyprint(node.tree, indent)
  File "./ppp_cli/prettyprint.py", line 89, in prettyprint
    return prettyprinter(node, indent+1)
  File "./ppp_cli/prettyprint.py", line 83, in jsonldresource
    prettyprint(node.graph, indent)
  File "./ppp_cli/prettyprint.py", line 89, in prettyprint
    return prettyprinter(node, indent+1)
  File "./ppp_cli/prettyprint.py", line 38, in dict
    prettyprint(value, indent)
  File "./ppp_cli/prettyprint.py", line 88, in prettyprint
    if isinstance(node, cls):
TypeError: isinstance() arg 2 must be a type or tuple of types
        @context:
```

**Comment by progval** [comment]
Sorry, I forgot to release the new version of ppp_datamodel.
Update it and it will work.
