### ISSUE TITLE
Print normal form in dot format: AttributeError: ('Sort', 0)

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/PPP-CLI#5]
Example: `What is the biggest country?`

```
digraph G {

Traceback (most recent call last):
  File "demo7.py", line 20, in <module>
    print_responses(getAnswer())
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_cli-0.1-py3.4.egg/ppp_cli/dot.py", line 44, in print_responses
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_cli-0.1-py3.4.egg/ppp_cli/dot.py", line 39, in print_tree
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.1-py3.4.egg/ppp_datamodel/nodes/list_operators.py", line 26, in traverse
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.1-py3.4.egg/ppp_datamodel/nodes/list_operators.py", line 25, in <listcomp>
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.1-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 75, in get
AttributeError: ('Sort', 0)
```

**Comment by progval** [comment]
Are you sure `ppp_datamodel` and `ppp_cli` are up to date?

**Comment by Ezibenroc** [comment]
Works for me:

```
digraph G {

n1 [ label = "country" ];
n2 [ label = "list" ];
n2 -> n1;
n3 [ label = "sort" ];
n3 -> n2 [ label = "list" ];
n4 [ label = "last" ];
n4 -> n3 [ label = "list" ];
}
```

You have to update your packages.
