### ISSUE TITLE
DOT format: do not ouptput a "list" node for inverse predicates when there is no inverse predicates

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/PPP-CLI#9]
Ex: 
![image](https://cloud.githubusercontent.com/assets/6659728/6247909/6a4d7c7c-b77a-11e4-9eb0-735ad4e8284c.png)

**Comment by progval** [comment]
Are you sure you want this? It will make the code far less readable

**Comment by yhamoudi** [comment]
As you want. Actually this is the trees that are less readable when the lists are empty.

**Comment by yhamoudi** [comment]
Thanks :) Is it normal:
![image](https://cloud.githubusercontent.com/assets/6659728/6250340/6eca9fce-b78d-11e4-8033-38e3ae8b0c4b.png)

**Comment by progval** [comment]
fixed

**Comment by yhamoudi** [comment]
I have another bug on `when was the president of france born` (tested with file `demo/demo7.py` of the question parsing):

``` bash
yassine@yassine-pc:~/ppp/PPP-QuestionParsing-Grammatical/demo$ python3 demo7.py when was the president of france born

digraph G {

Traceback (most recent call last):
  File "demo7.py", line 20, in <module>
    print_responses(getAnswer())
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_cli-0.2-py3.4.egg/ppp_cli/dot.py", line 53, in print_responses
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_cli-0.2-py3.4.egg/ppp_cli/dot.py", line 47, in print_tree
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.8-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 159, in traverse
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.8-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 160, in <dictcomp>
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.8-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 155, in wrapper
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.8-py3.4.egg/ppp_datamodel/nodes/list.py", line 37, in traverse
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.8-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 27, in __init__
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.8-py3.4.egg/ppp_datamodel/nodes/list.py", line 25, in _parse_attributes
AssertionError: [<PPP node "dotnode" {'label': 'born', 'name': 'n2', 'original': <PPP node "resource" {'value': 'born'}>}>, <PPP node "dotnode" {'label': 'birth', 'name': 'n3', 'original': <PPP node "resource" {'value': 'birth'}>}>, <PPP node "dotnode" {'label': 'born time', 'name': 'n4', 'original': <PPP node "resource" {'value': 'born time'}>}>, <PPP node "dotnode" {'label': 'born date', 'name': 'n5', 'original': <PPP node "resource" {'value': 'born date'}>}>, <PPP node "dotnode" {'label': 'birth time', 'name': 'n6', 'original': <PPP node "resource" {'value': 'birth time'}>}>, <PPP node "dotnode" {'label': 'birth date', 'name': 'n7', 'original': <PPP node "resource" {'value': 'birth date'}>}>]
```

**Comment by progval** [comment]
Oh, that explains why I implemented it like this… will fix it soon

**Comment by progval** [comment]
Fixed
